{% set name = "elephas" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e17eb933f7a69ae12115d39a80ec778a14ebf52c93027768dfe0f75449be326b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3

  run:
    - flask
    - keras
    - hyperas
    - pyspark
    - tensorflow
    - python >=3
    - six

test:
  imports:
    - docs
    - elephas
    - elephas.java
    - elephas.ml
    - elephas.mllib
    - elephas.parameter
    - elephas.utils

about:
  home: http://github.com/maxpumperla/elephas
  license: MIT
  license_file: LICENSE
  summary: Deep learning on Spark with Keras
  dev_url: http://github.com/maxpumperla/elephas

extra:
  recipe-maintainers:
    - Tata17
    - oblute
    - rluria14
