{% set name = "elephas" %}
{% set version = "3.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dbf58bf8d7626eb8a815e70f550f9442a0f6f246ec080717fe6293995e5927e7

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6

  run:
    - flask
    - keras
    - hyperas
    - pyspark
    - tensorflow
    - python >=3.6
    - six

test:
  imports:
    - docs
    - elephas
    - elephas.ml
    - elephas.mllib
    - elephas.parameter
    - elephas.utils

about:
  home: http://github.com/maxpumperla/elephas
  license: MIT
  license_file: LICENSE
  summary: Deep learning on Spark with Keras
  dev_url: http://github.com/maxpumperla/elephas

extra:
  recipe-maintainers:
    - oblute
    - rluria14
    - mxr-conda
