travis:
  secure:
    BINSTAR_TOKEN: QCkzgC5lm0Qpfh/zSiOtieiXNBVihCW3oaNRLNTKtXH8YNx55tmw8sX9xJ4jWKnL9X0mK/a5xCHd7hDqKFxHNsQNV5TbBPNQ5QBCigK6g8OQQ802rxEOwLOSKnUJkIte0bUYpUQpM71k+Jjfss4EOdCzoHYKqNL8Lo9F/XSH8SnAPDC72iGPc84PiEWMH9vw9SPf2kwKZFs9pieAOYeChRs7HcSX6d0b4SD4Vcv9MM3TUKJ6Sb3C9n8ATPVdOajc1lxrJRZN4F2lcuqK/Hs58HBQhc4uhCD+pJfAWIbNDAJyPgWp81tcEEVcyMPt//6UtY5kJlmTUuEF5tKOcvYvOtzyPx6d3XjDp2HT/sBy1bmbE1PX19jOPapOaAgi4CBhFlfoJAjfUSViY/2ulSOpoCLYtCaMUHwo2htCqwCLUnBZ+YtfA91C9i3KBa0k8t6+J2JITrnMfKojlUwKu/Uamq5hM8YCGSKspMvS6EasmGh9KaTG4SbDdHPLMCeyUuEIFb6VrK/OwMWzh1YT5SiSd1/GomXyLfY4Aahgfd8F7W1QcoOenOLgCSieWftlzkh5jF/HzGy/gsTvdD3jOkGpqz7/kbAkm3DQwE2waV7RjCmpqzYuzursdFnuQ0mufRdCIJq29D1cIDV4Ce7gYPtQgrqYz/PV+9TuyUmtYMG9zMc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
